# Generated by Django 5.2.17 on 2026-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('guide', 'Guide'), ('report', 'Report')], max_length=20)),
                ('slug', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('checksum', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-generated_at', '-updated_at', 'title'),
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='unique_document_kind_slug')],
            },
        ),
    ]
