# Generated by Django 5.2.17 on 2026-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_publisheddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportrun",
            name="card_html",
            field=models.TextField(blank=True, default=""),
        ),
    ]
