#!/usr/bin/env python3
"""Add an AllComponents process group holding every Quanifi processor.

Built for documentation screenshots: one instance of each processor class in
nifi_extensions/, laid out in labelled blocks by category, with no connections
between them.

Nothing here is guesswork. The tool imports each processor class through the
same nifiapi stubs the unit tests use and reads three things off it:

  * ProcessorDetails.version  -> the bundle version. These are NOT all the same
    (most are 0.1.0, a few 0.2.0, one 0.1.1), and a wrong version makes NiFi
    fail to resolve the type, which shows up as a ghost component rather than
    an error.
  * getRelationships()        -> every relationship is auto-terminated, so 80-odd
    unconnected processors do not each carry a validation warning in the
    screenshot. Processors that do not override it get the framework defaults
    (success, failure, original), which is what the live flow uses.
  * getPropertyDescriptors()  -> declared defaults are written into the
    processor's properties, so the components render configured rather than
    empty. Required properties with no default are left unset and reported at
    the end; those are the only ones that will still show as invalid.

Categories come from docs/COMPONENTS.md, so the screenshot matches the document
it illustrates. Processors not listed there (the 2026-08 hardware batch lane)
are classified by name and grouped under "Hardware batch lane".

NiFi must be stopped. A timestamped backup of the flow is written first.

BEFORE YOU RUN THIS, raise the Python process limits in conf/nifi.properties:

    nifi.python.max.processes=400                     # default 100
    nifi.python.max.processes.per.extension.type=20   # default 10

NiFi launches a Python process per processor instance. This group adds 83 of
them to a flow that already held 121, and at the default limit of 100 the
bridge exhausts its pool mid-startup: the main thread parks forever in
StandardPythonBridge.createProcessor -> getProcessorTypes, waiting on a py4j
lock held by a connection that is itself waiting on a Python process that can
never be launched. NiFi does not log an error, does not time out, and never
finishes starting -- the only symptom is that the log stops mid-initialisation
and the UI never answers. With the limits raised, the same flow starts in about
a minute.

Expect the first start after adding this group to be slow and to consume disk:
NiFi builds a separate virtualenv per processor type under work/python, and the
types that were not previously on the canvas each pull their own dependencies.

Even with the limits raised, adding all 83 at once is not reliable. Measured on
2026-08-19 against a flow already holding 121 Python processors: one start
succeeded in about 15 seconds, and two others wedged at the same place -- the
bridge initialises BraketSimulator, the Python side reports the process started
and pinged, and nothing happens afterwards. Same processor both times, so it is
ordering-dependent rather than random.

Hence --category. Adding one block at a time keeps the instance count near what
the flow already carries, which is the configuration known to start. For a full
set of screenshots, add a block, start NiFi, photograph it, remove it, and move
to the next.

Usage:
  python tools/add_all_components_group.py --flow ~/projects/nifi-2.9.0/conf/flow.json.gz
  python tools/add_all_components_group.py --flow ... --category "Simulators"
  python tools/add_all_components_group.py --flow ... --remove
  python tools/add_all_components_group.py --dry-run --list-categories
"""
import argparse
import gzip
import importlib
import inspect
import json
import re
import shutil
import sys
import uuid
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
sys.path.insert(0, str(ROOT / "experiments"))

from add_flow import make_processor, make_label  # noqa: E402

GROUP_NAME = "AllComponents"
GROUP_COMMENT = (
    "Every Quanifi processor, one instance each, no connections. Exists for "
    "documentation screenshots: blocks and labels follow the categories in "
    "docs/COMPONENTS.md. Generated by tools/add_all_components_group.py; edit "
    "the tool rather than the canvas, and re-run it after adding a processor."
)

# Clear of every existing group (the lowest is OfficialExperiment-HW at y=-3848).
GROUP_X, GROUP_Y = -25000.0, -4400.0

VALID_SCHEDULED_STATES = {"ENABLED", "DISABLED", "RUNNING"}
NOT_RUNNING = "ENABLED"

# Framework defaults when a processor does not override getRelationships().
# Confirmed against the running flow, where 34 python processors auto-terminate
# "original" alongside success/failure.
DEFAULT_RELATIONSHIPS = ("success", "failure", "original")

COL_W, ROW_H = 430.0, 190.0
BLOCK_GAP = 180.0
ROWS_PER_COL = 10
LABEL_H = 44.0


def uid():
    return str(uuid.uuid4())


# --------------------------------------------------------------------------
# discovery
# --------------------------------------------------------------------------

def install_stubs():
    """nifiapi stubs, plus a PropertyDescriptor that remembers `required`.

    The stub in tests/conftest.py keeps only name and default_value. The patch
    has to land before any processor module is imported, because they bind the
    class at import time.
    """
    import _harness  # noqa: F401  (side effect: stubs + extensions on sys.path)
    props = sys.modules["nifiapi.properties"]
    base = props.PropertyDescriptor

    class PropertyDescriptor(base):
        def __init__(self, name, description="", required=False,
                     default_value=None, **kwargs):
            super().__init__(name, description, required, default_value, **kwargs)
            self.required = bool(required)

    props.PropertyDescriptor = PropertyDescriptor


def discover():
    """Every processor class in nifi_extensions, with what the canvas needs."""
    install_stubs()
    found = []
    for path in sorted((ROOT / "nifi_extensions").glob("*.py")):
        if path.stem.startswith("_"):
            continue
        module = importlib.import_module(path.stem)
        for name, obj in vars(module).items():
            if not inspect.isclass(obj) or obj.__module__ != module.__name__:
                continue
            details = getattr(obj, "ProcessorDetails", None)
            if details is None or not hasattr(details, "version"):
                continue

            relationships, properties, missing = list(DEFAULT_RELATIONSHIPS), {}, []
            try:
                instance = obj()
            except Exception:
                instance = None

            if instance is not None and hasattr(instance, "getRelationships"):
                try:
                    declared = [r.name for r in instance.getRelationships()]
                    if declared:
                        # NiFi adds `failure` to a Python processor's own set: four
                        # processors here declare pass/fail or control_dissent and
                        # still carry a framework `failure` that has to be
                        # auto-terminated or the component is invalid.
                        if "failure" not in declared:
                            declared.append("failure")
                        relationships = declared
                except Exception:
                    pass

            if instance is not None and hasattr(instance, "getPropertyDescriptors"):
                try:
                    for d in instance.getPropertyDescriptors():
                        default = getattr(d, "default_value", None)
                        # An empty-string default is a "leave me unset" marker, not a
                        # value: writing it back fails validation on typed properties
                        # (Random Seed on the VQE and QAOA processors validates as an
                        # integer and rejects "").
                        if default is not None and str(default) != "":
                            properties[d.name] = str(default)
                        elif getattr(d, "required", False):
                            missing.append(d.name)
                except Exception:
                    pass

            found.append({
                "name": name,
                "version": details.version,
                "relationships": relationships,
                "properties": properties,
                "missing_required": missing,
                "deprecated": "deprecated" in (getattr(details, "description", "") or "").lower(),
            })
    return found


def categorise(processors):
    """Category per processor, from docs/COMPONENTS.md headings where possible."""
    doc = (ROOT / "docs" / "COMPONENTS.md")
    documented, category = {}, None
    if doc.exists():
        for line in doc.read_text(encoding="utf-8").splitlines():
            if line.startswith("## "):
                heading = line[3:].strip()
                category = None if heading == "Summary" else heading
            elif line.startswith("### ") and category:
                pass  # sub-headings stay inside their ## category
            elif line.startswith("| `") and category:
                m = re.match(r"\|\s*`([A-Za-z0-9_]+)`", line)
                if m:
                    documented[m.group(1)] = category

    def fallback(name):
        if re.search(r"Batch(Submitter|Poller|ResultExpander)|IQMJob|IBMBatch", name):
            return "Hardware batch lane"
        if re.search(r"Oracle|Assertion|Mutator|MutationScore|Comparison|TestCase", name):
            return "Differential & mutation-testing infrastructure"
        if re.search(r"Report|Unitary|Quanifi", name):
            return "Reporting & utility"
        if re.search(r"Simulator|Sampler|Device", name):
            return "Simulators"
        return "Other"

    for p in processors:
        p["category"] = documented.get(p["name"]) or fallback(p["name"])
    return processors


# --------------------------------------------------------------------------
# layout
# --------------------------------------------------------------------------

CATEGORY_ORDER = [
    "Circuit builders",
    "Hamiltonians & problem encoders",
    "Algorithms (all-in-one solvers)",
    "PennyLane QML lane",
    "Simulators",
    "Hardware execution",
    "Hardware batch lane",
    "Differential & mutation-testing infrastructure",
    "Reporting & utility",
    "Other",
]


def build_group(group_id, processors):
    """One labelled block per category, columns of ROWS_PER_COL, left to right."""
    by_category = {}
    for p in processors:
        by_category.setdefault(p["category"], []).append(p)

    ordered = [c for c in CATEGORY_ORDER if c in by_category]
    ordered += sorted(c for c in by_category if c not in CATEGORY_ORDER)

    nodes, labels = [], []
    x = 0.0
    for category in ordered:
        members = sorted(by_category[category], key=lambda p: p["name"])
        columns = (len(members) + ROWS_PER_COL - 1) // ROWS_PER_COL
        width = columns * COL_W

        labels.append(make_label(
            "%s  (%d)" % (category, len(members)),
            x, 0.0, width - 30.0, LABEL_H, group_id))

        for index, proc in enumerate(members):
            col, row = divmod(index, ROWS_PER_COL)
            nodes.append(make_processor(
                name=proc["name"],
                proc_type=proc["name"],
                bundle={"group": "org.apache.nifi",
                        "artifact": "python-extensions",
                        "version": proc["version"]},
                properties=proc["properties"],
                x=x + col * COL_W,
                y=LABEL_H + 36.0 + row * ROW_H,
                group_id=group_id,
                scheduled_state=NOT_RUNNING,
                auto_terminate=proc["relationships"],
            ))
        x += width + BLOCK_GAP
    return nodes, labels


# --------------------------------------------------------------------------

def group_name(category):
    if not category:
        return GROUP_NAME
    slug = re.sub(r"[^A-Za-z0-9]+", "", category.title())
    return "%s-%s" % (GROUP_NAME, slug)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--flow", help="path to flow.json.gz (NiFi must be stopped)")
    ap.add_argument("--category",
                    help="add only this category, as its own group. Adding all 83 "
                         "processors at once can wedge the Python bridge on "
                         "startup; one block at a time is the reliable path.")
    ap.add_argument("--list-categories", action="store_true",
                    help="print the category names --category accepts")
    ap.add_argument("--remove", action="store_true", help="delete the group instead")
    ap.add_argument("--dry-run", action="store_true",
                    help="discover and report, touch no files")
    args = ap.parse_args()

    processors = categorise(discover())
    if args.category:
        known = {p["category"] for p in processors}
        if args.category not in known:
            raise SystemExit("unknown category %r; known: %s"
                             % (args.category, sorted(known)))
        processors = [p for p in processors if p["category"] == args.category]
    print("discovered %d processors" % len(processors))
    counts = {}
    for p in processors:
        counts[p["category"]] = counts.get(p["category"], 0) + 1
    for category in sorted(counts, key=lambda c: (-counts[c], c)):
        print("  %-48s %d" % (category, counts[category]))

    versions = {}
    for p in processors:
        versions.setdefault(p["version"], []).append(p["name"])
    print("bundle versions: %s" % {v: len(n) for v, n in sorted(versions.items())})

    incomplete = [p for p in processors if p["missing_required"]]
    if incomplete:
        print("\n%d processors have required properties with no default; they will "
              "show as invalid until configured:" % len(incomplete))
        for p in sorted(incomplete, key=lambda p: p["name"]):
            print("  %-34s %s" % (p["name"], ", ".join(p["missing_required"])))

    if args.list_categories:
        return
    if args.dry_run:
        return
    if not args.flow:
        raise SystemExit("--flow is required unless --dry-run")

    flow_path = Path(args.flow).expanduser()
    if not flow_path.exists():
        raise SystemExit("no such flow file: %s" % flow_path)

    backup = flow_path.with_name(
        "%s.bak_allcomponents_%s"
        % (flow_path.name, datetime.now().strftime("%Y%m%d_%H%M%S_%f")))
    shutil.copy2(flow_path, backup)
    with gzip.open(flow_path, "rt", encoding="utf-8") as handle:
        flow = json.load(handle)

    root = flow["rootGroup"]
    groups = root.setdefault("processGroups", [])
    name = group_name(args.category)
    existing = [g for g in groups if g.get("name") == name]

    if args.remove:
        if not existing:
            raise SystemExit("group not present: %s" % name)
        groups[:] = [g for g in groups if g.get("name") != name]
        action = "removed"
    else:
        if existing:
            raise SystemExit("group already exists: %s (use --remove first)" % name)
        group_id = uid()
        nodes, labels = build_group(group_id, processors)
        bad = sorted({n["scheduledState"] for n in nodes} - VALID_SCHEDULED_STATES)
        if bad:
            raise SystemExit("refusing to write: invalid scheduledState %s" % bad)
        groups.append({
            "identifier": group_id,
            "instanceIdentifier": uid(),
            "name": name,
            "comments": GROUP_COMMENT,
            "position": {"x": GROUP_X, "y": GROUP_Y},
            "processGroups": [], "remoteProcessGroups": [],
            "processors": nodes, "connections": [],
            "inputPorts": [], "outputPorts": [], "labels": labels, "funnels": [],
            "controllerServices": [],
            "defaultFlowFileExpiration": "0 sec",
            "defaultBackPressureObjectThreshold": 10000,
            "defaultBackPressureDataSizeThreshold": "1 GB",
            "scheduledState": "ENABLED",
            "executionEngine": "INHERITED",
            "maxConcurrentTasks": 1,
            "statelessFlowTimeout": "1 min",
            "flowFileOutboundPolicy": "STREAM_WHEN_AVAILABLE",
            "flowFileConcurrency": "UNBOUNDED",
            "componentType": "PROCESS_GROUP",
            "groupIdentifier": root["identifier"],
        })
        action = "added %d processors, %d labels, 0 connections" % (len(nodes), len(labels))

    with gzip.open(flow_path, "wt", encoding="utf-8") as handle:
        json.dump(flow, handle)

    if not args.remove:
        print("\nNOTE: NiFi launches one Python process per processor instance. "
              "Check that\n      nifi.python.max.processes in conf/nifi.properties "
              "exceeds the total\n      number of Python processors in the flow, or "
              "NiFi will hang on startup\n      with no error (see this file's "
              "docstring).")

    print("\n%s: %s" % (name, action))
    print("flow  : %s" % flow_path)
    print("backup: %s" % backup)
    if not args.remove:
        print("\nStart NiFi and open %s at (%d, %d). Everything is stopped; "
              "nothing will run." % (name, GROUP_X, GROUP_Y))


if __name__ == "__main__":
    main()
